adding digestSend
freeverseio/market-signer pull request #56
Opened 2023-05-29 06:30 UTC by kudlaj

2023-05-29 13:40 UTC, tonimateos requested changes

2023-05-29 13:40 UTC, tonimateos commented on test/MarketSigner.test.js
> +  const sigSeller = sign({ digest, web3account: sellerAccount });
Can you please also add an explicit check for the return of the digest? I know in most tests we only check the signature, but it'd be great to test explicitly the function that we actually export and want others to use.

2023-05-29 14:48 UTC, AlexRipoll approved these changes

2023-05-30 08:41 UTC, tonimateos approved these changes
Great, the digests now match with other repos.

2023-05-30 13:57 UTC, luispdm approved these changes

2023-07-12 07:59 UTC, tonimateos approved these changes

2023-07-12 07:59 UTC, merged